# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${XDEBUG}'
                XDEBUG_PORT: '${XDEBUG_PORT}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            PHP_IDE_CONFIG: serverName=Docker
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
    postgres:
        image: 'postgres:15.0'
        restart: always
        environment:
            POSTGRES_USERNAME: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        networks:
            - sail
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'

networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
