apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: random-name-schedule-deply
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: schedule
              image: 861085574061.dkr.ecr.eu-central-1.amazonaws.com/route_runner:latest
              command: [ "php", "artisan", "schedule:run"]
          restartPolicy: OnFailure
