name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    #PostgresSQL
    runs-on: ubuntu-latest
    services: 
      postgres:
          image: postgres
          env: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
          ports:
            - 5432/tcp
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Dependencies
        run: composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Run test with coverage
      - name: Migrate
        env: 
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # The default PostgreSQL port
          DB_PORT: ${{job.services.postgres.ports['5432']}}
          DB_HOST: "127.0.0.1"

        run: php artisan migrate -v
        run: |
          php artisan test --coverage-html reports/
        env:
        # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # The default PostgreSQL port
          DB_PORT: ${{job.services.postgres.ports['5432']}}
          DB_HOST: "127.0.0.1"

